import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const seStyles = StyleSheet.create({
  // ── Opponent area ──────────────────────────────────────
  opponentArea: {
    marginTop: 16,
    paddingHorizontal: 16,
  },
  playerPanel: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 41, 59, 0.8)',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  playerIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  myAvatarCircle: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  playerMeta: {
    flex: 1,
    gap: 4,
  },
  playerName: {
    color: '#F8FAFC',
    fontSize: 15,
    fontWeight: '700',
  },
  myPlayerName: {
    color: '#F8FAFC',
    fontSize: 15,
    fontWeight: '700',
  },
  roleBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  myRoleBadge: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  roleText: {
    color: '#F59E0B',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  myRoleText: {
    color: '#34D399',
  },
  trickCounter: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    gap: 1,
  },
  trickBig: {
    color: '#38BDF8',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  trickOf: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 24,
  },
  trickCaption: {
    color: '#64748B',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
    alignSelf: 'flex-end',
    marginBottom: 1,
    marginLeft: 3,
  },

  // ── Play area ──────────────────────────────────────────
  playArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trumpIndicator: {
    position: 'absolute',
    top: 12,
    left: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(30, 41, 59, 0.8)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  trumpLabel: {
    color: '#94A3B8',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  trumpSuitSymbol: {
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
  },
  turnBadge: {
    position: 'absolute',
    top: 12,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
  },
  turnBadgeMine: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderColor: 'rgba(16, 185, 129, 0.35)',
  },
  turnBadgeOpp: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  turnDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  turnBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  trickZone: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 180,
    height: 320,
  },
  tableRing: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  trickWinnerBadge: {
    position: 'absolute',
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
  },
  trickWinnerText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  cardSlot: {
    width: 110,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
  },
  slotDivider: {
    width: 48,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    marginVertical: 4,
  },
  emptySlot: {
    width: 82,
    height: 118,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  emptySlotActive: {
    borderColor: 'rgba(16, 185, 129, 0.6)',
    backgroundColor: 'rgba(16, 185, 129, 0.07)',
  },
  emptySlotLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.5,
  },

  // ── My area ────────────────────────────────────────────
  myArea: {
    paddingBottom: 24,
  },
  myInfoBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 0,
    zIndex: 10,
  },
  myTrickCounter: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: 'rgba(0,0,0,0.35)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    gap: 1,
  },
  myTrickBig: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  myTrickOf: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 24,
  },
  myTrickCaption: {
    color: '#475569',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
    alignSelf: 'flex-end',
    marginBottom: 1,
    marginLeft: 3,
  },
  handContainer: {
    height: 230,
    width: '100%',
    overflow: 'visible',
  },
  handScroll: {
    paddingHorizontal: 36,
    alignItems: 'flex-end',
    justifyContent: 'center',
    flexGrow: 1,
    overflow: 'visible',
    paddingBottom: 40,
  },

  // ── Modal shared ───────────────────────────────────────
  modalTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 6,
  },
  modalSub: {
    color: '#94A3B8',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 20,
  },

  // ── Rules modal ────────────────────────────────────────
  ruleBody: {
    color: '#CBD5E1',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  ruleExample: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    padding: 12,
    borderRadius: 14,
    gap: 12,
  },
  ruleExampleItem: {
    alignItems: 'center',
    gap: 6,
  },
  ruleExampleLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#94A3B8',
    letterSpacing: 0.8,
  },
  ruleVs: {
    color: '#64748B',
    fontWeight: '800',
    fontSize: 12,
  },
  strengthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 2,
  },
  strengthLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#F59E0B',
    marginRight: 4,
    letterSpacing: 0.5,
  },
  winGoalRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderRadius: 14,
    padding: 16,
    marginTop: 10,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  winGoal: {
    alignItems: 'center',
    gap: 2,
  },
  winGoalRole: {
    fontSize: 10,
    fontWeight: '900',
    color: '#64748B',
    letterSpacing: 0.8,
  },
  winGoalNumber: {
    fontSize: 36,
    fontWeight: '900',
    color: '#10B981',
    lineHeight: 40,
  },
  winGoalUnit: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
  },
  winGoalDivider: {
    width: 1,
    height: 50,
    backgroundColor: '#E2E8F0',
  },

  // ── Trump selection modal ──────────────────────────────
  suitGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
    marginTop: 4,
  },
  suitBtn: {
    width: 80,
    height: 80,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  suitIcon: {
    fontSize: 30,
    lineHeight: 36,
  },
  suitName: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: '#F8FAFC',
  },
  waitingContainer: {
    alignItems: 'center',
    gap: 12,
  },
  waitingIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ── Game over modal ────────────────────────────────────
  resultHero: {
    width: '100%',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 20,
    borderRadius: 16,
    marginBottom: 16,
  },
  resultTitle: {
    fontSize: 26,
    fontWeight: '900',
  },
  resultSub: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
  },
  scoreBreakdown: {
    width: '100%',
    gap: 8,
    marginBottom: 16,
  },
  scoreBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scoreBreakdownLabel: {
    width: 28,
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
  },
  scoreBreakdownBar: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    flexDirection: 'row',
    overflow: 'hidden',
    backgroundColor: '#E2E8F0',
  },
  scoreBarFill: {
    height: 8,
  },
  scoreBreakdownNum: {
    width: 40,
    color: '#0F172A',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  historySection: {
    width: '100%',
    marginBottom: 16,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  historySectionTitle: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  seriesPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 41, 59, 0.8)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  seriesNum: {
    fontSize: 15,
    fontWeight: '900',
    color: '#F8FAFC',
  },
  seriesDash: {
    color: '#94A3B8',
    fontWeight: '700',
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    gap: 8,
  },
  historyRound: {
    width: 28,
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
  },
  historyResultDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  historyScore: {
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
  },
  historyOutcome: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '600',
  },
  gameOverActions: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
});
